## pyLisa Tutorial

In [2]:
import sapy.modal as sa
import sapy.post as po
import sapy.sensitivity as sn
import pdb as pdb

option = {'flow': 'DATA/G.txt',
          'n_points': 200,
          'lc': 0.16739,
          'Ymax': 1000,
          'yi': 10,
          'alpha': 0.6,
          'Re': 160,
          'variables': 'v_eta',
          'equation': 'Euler_CD',
          'mapping': ['semi_infinite_PB', [0, (46.7/13.8)]],
          'Froude': 0.02,
          'slope': 1.3e-5}


f = sa.fluid(option)

f.diff_matrix()
f.read_velocity_profile()
f.mapping()
f.interpolate()
# f.set_blasisus(f.y)

# f.infinite_mapping()
# f.set_hyptan()
# f.set_poiseuille()

f.set_operator_variables()

f.solve_eig()
f.adjoint_spectrum_v_eta('cont')
f.solve_eig_adj()

f.save_sim('200_ve_cont')
f.check_adj()




v = po.viz('200_ve_cont.npz')
v.plot_velocity()
v.plot_spectrum()
# f.omega_alpha_curves(0.0001,2,5

om = sn.sensitivity(0.1, '200_ve_cont.npz', 16)
#om.u_pert(0.4, 0.2)
#om.cd_pert(0.5, 0.1)
#om.c_per()

#om.sens_spectrum('ke_u_N01_ve.png', per_variab='u')
om.validation(0.2, 0.2)


(-6723186936.05-2646071639.89j) (-18.103174802-52.1978418557j)
new: (0.923233059519+0.0804003326809j)
old: (0.922267707315+0.0796036519505j)
diff: (0.000965352204411+0.000796680730408j)
(5.48246507258e-05-0.000297631304481j)


In [2]:
import numpy as np
from __future__ import division

In [57]:
 def clencurt(N):
    """ CLENCURT  nodes x (Chebyshev points) and weights 
    for Clenshaw-Curtis quadrature"""
    
    theta = np.pi*np.arange(0,N+1) / N
    x = np.cos(theta)
    w = np.zeros(N+1) 
    ii = np.arange(1,N) 
    v = np.ones(N-1)
    if np.mod(N, 2) == 0:
        w[0] = 1/ (N**2 -1)
        w[-1] = w[0]
        for k in np.arange(1, N/2):
                v = v - 2*np.cos(2*k*theta[ii])/(4* k**2 -1)
        v = v - np.cos(N*theta[ii])/(N**2-1)
    else:
        w[0] = 1/ N**2
        w[-1] = w[0]
        for k in np.arange(1, N/2):
            v = v - 2*np.cos(2*k*theta[ii])/(4* k**2 -1) 
    w[ii] = 2*v/N
    return x,w
    

In [180]:
N = 40
x, W = clencurt(N)

In [181]:
x

array([  1.00000000e+00,   9.96917334e-01,   9.87688341e-01,
         9.72369920e-01,   9.51056516e-01,   9.23879533e-01,
         8.91006524e-01,   8.52640164e-01,   8.09016994e-01,
         7.60405966e-01,   7.07106781e-01,   6.49448048e-01,
         5.87785252e-01,   5.22498565e-01,   4.53990500e-01,
         3.82683432e-01,   3.09016994e-01,   2.33445364e-01,
         1.56434465e-01,   7.84590957e-02,   6.12323400e-17,
        -7.84590957e-02,  -1.56434465e-01,  -2.33445364e-01,
        -3.09016994e-01,  -3.82683432e-01,  -4.53990500e-01,
        -5.22498565e-01,  -5.87785252e-01,  -6.49448048e-01,
        -7.07106781e-01,  -7.60405966e-01,  -8.09016994e-01,
        -8.52640164e-01,  -8.91006524e-01,  -9.23879533e-01,
        -9.51056516e-01,  -9.72369920e-01,  -9.87688341e-01,
        -9.96917334e-01,  -1.00000000e+00])

In [182]:
W

array([ 0.00062539,  0.00601557,  0.01233804,  0.01830902,  0.02428549,
        0.03004565,  0.0356637 ,  0.04103133,  0.046169  ,  0.05100387,
        0.05553914,  0.05971946,  0.06354242,  0.06696406,  0.06998145,
        0.0725595 ,  0.07469753,  0.07636811,  0.07757446,  0.07829613,
        0.07854138,  0.07829613,  0.07757446,  0.07636811,  0.07469753,
        0.0725595 ,  0.06998145,  0.06696406,  0.06354242,  0.05971946,
        0.05553914,  0.05100387,  0.046169  ,  0.04103133,  0.0356637 ,
        0.03004565,  0.02428549,  0.01830902,  0.01233804,  0.00601557,
        0.00062539])

In [191]:
f = x**2
I = W*f
print np.sum(I)

0.666666666667


In [192]:
a = -np.pi
b = +np.pi
y = (b - a) * 0.5 * x + (a + b) * 0.5
#xi = np.zeros(N)
xi = np.ones(N+1)*( (b-a)/2)
Wn = xi *  W


In [193]:
f = y**2
I = Wn*f
print np.sum(I)

20.6708511202


In [169]:
np.ones(8)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [163]:
x

array([  1.00000000e+00,   9.96917334e-01,   9.87688341e-01,
         9.72369920e-01,   9.51056516e-01,   9.23879533e-01,
         8.91006524e-01,   8.52640164e-01,   8.09016994e-01,
         7.60405966e-01,   7.07106781e-01,   6.49448048e-01,
         5.87785252e-01,   5.22498565e-01,   4.53990500e-01,
         3.82683432e-01,   3.09016994e-01,   2.33445364e-01,
         1.56434465e-01,   7.84590957e-02,   6.12323400e-17,
        -7.84590957e-02,  -1.56434465e-01,  -2.33445364e-01,
        -3.09016994e-01,  -3.82683432e-01,  -4.53990500e-01,
        -5.22498565e-01,  -5.87785252e-01,  -6.49448048e-01,
        -7.07106781e-01,  -7.60405966e-01,  -8.09016994e-01,
        -8.52640164e-01,  -8.91006524e-01,  -9.23879533e-01,
        -9.51056516e-01,  -9.72369920e-01,  -9.87688341e-01,
        -9.96917334e-01,  -1.00000000e+00])

In [154]:
x

array([  1.00000000e+00,   9.96917334e-01,   9.87688341e-01,
         9.72369920e-01,   9.51056516e-01,   9.23879533e-01,
         8.91006524e-01,   8.52640164e-01,   8.09016994e-01,
         7.60405966e-01,   7.07106781e-01,   6.49448048e-01,
         5.87785252e-01,   5.22498565e-01,   4.53990500e-01,
         3.82683432e-01,   3.09016994e-01,   2.33445364e-01,
         1.56434465e-01,   7.84590957e-02,   6.12323400e-17,
        -7.84590957e-02,  -1.56434465e-01,  -2.33445364e-01,
        -3.09016994e-01,  -3.82683432e-01,  -4.53990500e-01,
        -5.22498565e-01,  -5.87785252e-01,  -6.49448048e-01,
        -7.07106781e-01,  -7.60405966e-01,  -8.09016994e-01,
        -8.52640164e-01,  -8.91006524e-01,  -9.23879533e-01,
        -9.51056516e-01,  -9.72369920e-01,  -9.87688341e-01,
        -9.96917334e-01,  -1.00000000e+00])

In [111]:
import matplotlib.pyplot as plt

In [112]:
plt.plot(y,f)
plt.show()

In [113]:
from scipy.integrate import trapz
print trapz(y,f)

2.25514051877e-17
